version: '3.8'
services:
  pineapple-playground:
    build: .
    restart: always
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - 'traefik.http.routers.pineappleplayground.rule=Host(`pineappleplayground.localhost`)'
    volumes:
      - ./playground/src:/var/www/html/public
      - ./pineapple/dist:/var/www/html/public/pineapple
      - ./templates:/var/www/html/public/templates

networks:
  traefik:
    name: traefik
